### PR TITLE
AbstractSkeletonCreator subclasses create now consistent line endings.

### LINKED ISSUE #376: Tests are broken on Windows
Tests introduced in #328 are breaking on Windows due to incompatible line-breaks in the text files.

### Expected Behavior
All tests should pass on all platforms

### Current Behavior
Tests fail on Windows

### Steps to Reproduce
1.  Get your hands on a Windows machine
2. Checkout scenebuilder
3. Run `mvn verify`

### Your Environment
Windows 10 + JDK 11

### Screenshots
NA

### PR DESCRIPTION
**Pull request by Oliver-Loeffler**
Fixes the broken tests for FXML controller sekeleton creation on Windows. 
Root cause was a hard coded `\n` in `ImportBuilder` class. The job of creating import lines for Kotlin and Java is now delegated to AbstractSkeletonCreator subclasses.

### Issue

Fixes #376

### Progress

- [ ] Change must not contain extraneous whitespace
- [ ] License header year is updated, if required
- [ ] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

**Comment by Oliver-Loeffler** [comment]
Having the imports updated was a mistake - I will revert this if needed.

**Comment by abhinayagarwal** [comment]
Hi @Oliver-Loeffler ,

Can you update the PR to integrate https://github.com/gluonhq/scenebuilder/pull/379 ?

**Comment by Oliver-Loeffler** [comment]
Yes. I can do so.

**Comment by Oliver-Loeffler** [comment]
Issue-378 is now merged into issue-376. GitHub Action is really cool in this regard, seems to work.

**Comment by abhinayagarwal** [comment]
I am not sure how the commit made in #379 is showing as a part of the PR. @Oliver-Loeffler can you fix this?

**Comment by Oliver-Loeffler** [comment]
Hi @abhinayagarwal , 
I'm not really sure about the question. Shall I rework the commit message or the PR description?
Thanks!

**Comment by abhinayagarwal** [comment]
When I asked you to [update the PR](https://github.com/gluonhq/scenebuilder/pull/377#issuecomment-887297734), did you getch and merge `gluonhq/master` branch into `issue-376` branch of your fork? or did you do something else?

**Comment by Oliver-Loeffler** [comment]
Well, I fetched and merged from here: https://github.com/abhinayagarwal/scenebuilder/tree/issue-378
I can revert and do this with the `gluonhq/master`.

**Comment by abhinayagarwal** [comment]
Aha, that's it. Yes, you must remove the commit from `abhinayagarwal/issue-378` and merge `gluonhq/master` instead.

**Comment by Oliver-Loeffler** [comment]
Sorry for the confusion. Did not see, that it was already in master - I will be more careful in future with that. The reworked PR is there.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/eventnames/ImportBuilder.java [hunk 1]
```diff
@@ -46,18 +79,15 @@ public static boolean isEmpty() {
...
-        imports.forEach((key, value) -> {
-            sb.append(key);
-            sb.append(value);
-            sb.append(";\n");
-        });
-        return sb.toString();
+    public static List<String> build() {
+        return imports.entrySet()
+               .stream()
+               .map(imprt->imprt.getKey()+imprt.getValue())
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/eventnames/ImportBuilder.java:90]: use blank spaces, and probably better to rename `imprt` to `import`

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonBufferTest.java [hunk 2]
```diff
@@ -54,7 +54,7 @@ public void testControllerWithoutPackageName() throws IOException {
         String skeleton = skeletonBuffer.toString();
 
         // then
-        String firstLine = skeleton.substring(0, skeleton.indexOf("\n"));
+        String firstLine = skeleton.substring(0, skeleton.indexOf(System.lineSeparator()));
```
Comment (jperedadnr) [inline kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonBufferTest.java:57]: We already have `NL` defined in `AbstractSkeletonCreator`, use it.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/eventnames/ImportBuilder.java (hunk 1 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/eventnames/ImportBuilder.java]: As `import` is a reserved word, I decided for `preparedImport`, something like `importEntry` would also work.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/eventnames/ImportBuilder.java [hunk 3]
```diff
@@ -46,18 +79,15 @@ public static boolean isEmpty() {
...
-        imports.forEach((key, value) -> {
-            sb.append(key);
-            sb.append(value);
-            sb.append(";\n");
-        });
-        return sb.toString();
+    public static List<String> build() {
+        return imports.entrySet()
+               .stream()
+               .map(preparedImport->preparedImport.getKey()+preparedImport.getValue())
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/eventnames/ImportBuilder.java:90]: ok, but still need some blank spaces

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/eventnames/ImportBuilder.java [hunk 4]
```diff
@@ -46,18 +79,15 @@ public static boolean isEmpty() {
...
-        imports.forEach((key, value) -> {
-            sb.append(key);
-            sb.append(value);
-            sb.append(";\n");
-        });
-        return sb.toString();
+    public static List<String> build() {
+        return imports.entrySet()
+                      .stream()
+                      .map(preparedImport->preparedImport.getKey()+preparedImport.getValue())
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/eventnames/ImportBuilder.java:90]: I didn't mean indentation (it was fine), but white/blank spaces in the lambda expression, like:
```
.map(preparedImport -> preparedImport.getKey() + preparedImport.getValue())
```

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonBufferTest.java [hunk 5]
```diff
@@ -54,7 +54,7 @@ public void testControllerWithoutPackageName() throws IOException {
         String skeleton = skeletonBuffer.toString();
 
         // then
-        String firstLine = skeleton.substring(0, skeleton.indexOf("\n"));
+        String firstLine = skeleton.substring(0, skeleton.indexOf(AbstractSkeletonCreator.NL));
```
Comment (jperedadnr) [inline kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonBufferTest.java:57]: Better now. 
Since you have a single `NL` entry, have you tried setting `NL = "\n"` ? Does it pass the tests?

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/eventnames/ImportBuilder.java (hunk 3 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/eventnames/ImportBuilder.java]: Spaces have now been added to the lambda.

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonBufferTest.java (hunk 5 above)
Comment (Oliver-Loeffler) [reply kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonBufferTest.java:57]: When running with "\n", tests will pass on MacOS and Linux. On Window tests will fail.

**Review by jperedadnr — APPROVED** [review]

**Review by abhinayagarwal — APPROVED** [review]
