### PR TITLE
Skip update check in developer mode

### LINKED ISSUE #352: Popup with failed Update Check in Dev Mode
When starting SceneBuilder locally from master an error popup for a failed "Update Check" is shown.
It states in the text that this is probably due to "Version number format not supported. Maybe using SNAPSHOT or RC versions".
If starting SceneBuilder frequently this gets annoying.
Additionally, the main window size changes and is smaller when the popup shows up.

### Expected Behavior
No error popup is shown. The main window size is not changed.

### Current Behavior
An error popup "Update check" is shown. The main window size is reduced.

### Steps to Reproduce
1. Start SceneBuilder with `mvn javafx:run -f app`.
2. Close the window with the recent FXML files opened (title "Gluon Scene Builder").
3. Error popup should appear. Size of the main window is changed.
 
### Your Environment
SceneBuilder built from master
Linux

### Screenshots
scenebuilder_update_check

### PR DESCRIPTION
**Pull request by abhinayagarwal**
Fixes #352

### CODE REVIEW

File: app/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java [hunk 1]
```diff
@@ -1011,7 +1013,7 @@ private void showVersionNumberFormatError(DocumentWindowController dwc) {
         // in development so we don't localize the strings
         alert.setTitle("Error");
         alert.setHeaderText(I18N.getString("check_for_updates.alert.headertext"));
-        alert.setContentText("Version number format not supported. Maybe using SNAPSHOT or RC versions.");
+        alert.setContentText("Update check is disabled in development environment.");
```
Comment (jperedadnr) [inline app/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java:1016]: The new snapshot check doesn't throw NFE. If it is not a snapshot, and while checking the version there is a NFE, the error message should still be `Version number format not supported`.

Comment (abhinayagarwal) [reply app/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java:1016]: The new snapshot will not throw NFE during startup. However, it will throw if a user goes selects "Check for updates.." from the Help menu.

**Review by jperedadnr — APPROVED** [review]
