### PR TITLE
fix: Enables Scene Builder to provide Insets editor for custom controls

### LINKED ISSUE #532: Error Custom StyleableProperty In SceneBuilder
### Screenshots

Welcome
I encountered a problem while creating a custom property in scene builder where I can't get this property, so please give me a solution to this problem as soon as possible if possible
You can watch this picture in order to understand what I want to say
Currently this property
bandicam 2022-03-26 18-48-18-613

bandicam 2022-03-26 18-48-18-613

And here this property does not appear in scene builder
bandicam 2022-03-26 18-50-07-685

I wanna get like this in scene builder
bandicam 2022-03-26 19-04-53-566

### PR DESCRIPTION
**Pull request by Oliver-Loeffler**
Enables editing of Insets properties in properties editor.
The `MetadataIntrospector` has been updated accordingly. The insets defaults are read from the introspected bean.

I'll add a test for this in a follow up commit. Ideally I'd like to move the functionality of `makePropertyMetadata` method into a separate class.

### Issue

Fixes #532

### Progress

- [x] Change must not contain extraneous whitespace
- [x] License header year is updated, if required
- [x] The PR name must follow the [pre-defined format](https://github.com/gluonhq/scenebuilder/blob/master/CONTRIBUTING.md)
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/MetadataIntrospector.java [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2016, 2022, Gluon and/or its affiliates.
+ * Copyright (c) 2016, 2023, Gluon and/or its affiliates.
```
Comment (abhinayagarwal) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/MetadataIntrospector.java:2]: can you update the license year to 2024?

**Review by abhinayagarwal — APPROVED** [review]
Overall the changes look good to me.

**Review by abhinayagarwal — APPROVED** [review]

**Comment by Oliver-Loeffler** [comment]
Thanks @abhinayagarwal. I'wasnt fast enough for changing the license year. Well, but within next days I'll be able to review and rework the other open items.
