### PR TITLE
fix: xdg-open is now used to reveal a file Linux file system (#674)

### LINKED ISSUE #674: Opening the OS-supplied File Manager (other than Nautilus) fail
Commands that require launching the OS File Manager fail with the following exception:
`java.io.IOException: Cannot run program "nautilus": error=2, No such file or directory`.

I tried
 - File > Reveal on Desktop
 - File > Include > Reveal <fileName> in Explorer

### Expected Behavior
The OS-supplied File Manager application should open at that file's location and with that file selected.

### Current Behavior
The following exception is thrown: `java.io.IOException: Cannot run program "nautilus": error=2, No such file or directory`.
The error message popping up at "Reveal <fileName> in Explorer" is misleading (it says "File <fullFilePath> cannot be found" instead of "Could not reveal <fileName> / <filePath>".

### Steps to Reproduce
- On a Linux distribution with a file manager other than Nautilus, open the Scene Builder application
- Create and save an FXML file (CHILD_FILE.FXML) - **do not close Scene Builder**
- _Reproduce the issue on "Reveal on Desktop"_ by accessing File > Reveal on Desktop
- Create and save another FXML file (PARENT_FILE.FXML) - this instance can be closed
- Include CHILD_FILE.FXML into PARENT_FILE.FXML
- In the left-hand side of the editor, in the Document > Hierarchy section, select the included file
- _Reproduce the issue on "Reveal <fileName> in Explorer"_ by accessing File > Include > Edit 'CHILD_FILE.FXML' in Explorer

### Environment
OS: Kubuntu 22.04; file manager: Dolphin 21.12.3

Scene Builder Product Version
JavaFX Scene Builder 21.0.0

Build Information
Version 21.0.0
Date: 2023-10-05 12:11:04
JavaFX Version: 21
Java Version: 21, OpenJDK Runtime Environment

### PR DESCRIPTION
**Pull request by Oliver-Loeffler**
This PR removes the call to `nautilus` as file browser and makes use of `xdg-open` instead.
On most recent Linux OS, a call to `xdg-open /home/user/myfxmls` will open the directory in a file browser which is specific to the OS and desktop environment.

There is one part missing yet, the error handling. Its complained that only an `IOException` is reported. This is indeed quite misleading. A subsequent update of this PR will introduce proper message dialog and show whats wrong.

### Issue

Fixes #674

### Progress

- [x] Change must not contain extraneous whitespace
- [X] License header year is updated, if required
- [X] The PR name must follow the [pre-defined format](https://github.com/gluonhq/scenebuilder/blob/master/CONTRIBUTING.md)
- [X] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

**Comment by Oliver-Loeffler** [comment]
Instead of Nautilus, `xdg-open` is now used to open a file system view on Linux. Also, the actual return code of the cmd calls used is now evaluated. In case of error, this is reported to the user. Furthermore, all error dialogs for related `open`, `reveal` and `edit` operations now look the same (short error message, Scene Builder icon, a details window with the stack trace).  Logging has been added where it seemed useful.

File: app/src/main/java/com/oracle/javafx/scenebuilder/app/DocumentWindowController.java [hunk 1]
```diff
@@ -2275,17 +2286,64 @@ private void performHelp() {
...
+        errorDialog.setTitle(I18N.getString("alert.error.resource.reveal.title"));
+        errorDialog.setMessage(I18N.getString("alert.error.resource.reveal.message"));
+        errorDialog.setDetails(I18N.getString("alert.error.resource.reveal.details", locationToBeRevealed));
+        errorDialog.setDetailsTitle(I18N.getString("alert.error.resource.reveal.details.title"));
+        errorDialog.setDebugInfoWithThrowable(revealException);
+        errorDialog.showAndWait();
+    }
+    
+    /**
+     *
```
Comment (jperedadnr) [inline app/src/main/java/com/oracle/javafx/scenebuilder/app/DocumentWindowController.java:2334]: remove empty line

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorController.java [hunk 2]
```diff
@@ -2331,14 +2331,15 @@ private void performEditIncludedFile() {
...
+        } catch (IOException re) {
+            final ErrorDialog errorDialog = new ErrorDialog(this.ownerWindow);
+            errorDialog.setTitle(I18N.getString("alert.error.file.open.title"));
+            errorDialog.setMessage(I18N.getString("alert.error.file.open.edit.message"));
+            errorDialog.setDetails(I18N.getString("alert.error.file.reveal.details", includedFile.getAbsolutePath()));
+            errorDialog.setDetailsTitle(I18N.getString("alert.error.file.open.edit.details.title"));
+            errorDialog.setDebugInfoWithThrowable(re);
             errorDialog.showAndWait();
-        }
+        }
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorController.java:2342]: remove extra white space after curly brace.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java [hunk 3]
```diff
@@ -331,54 +344,44 @@ public static void open(String path) throws IOException {
...
             }
             args.add(path);
         } else {
             // Not Supported
+            LOGGER.log(Level.SEVERE, "Unsupported operating system! Cannot reveal location {0} in file browser.", path);
         }
 
         if (!args.isEmpty()) {
-            executeDaemon(args, null);
+            executeDaemon(args, null, exitCodeOk);
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java:384]: question: are we running this from the JavaFX thread? It should be done in a background thread if that was the case.

File: kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit.properties [hunk 4]
```diff
@@ -430,10 +430,19 @@ error.file.create.title = File creation failed
 # {0} is a file path
 error.file.create.message = File {0} cannot be created
 error.file.open.message = File {0} cannot be opened
-error.file.open.title = File opening failed
 error.write.details = Please check your file system.
-error.file.reveal.title = File locating failed
-error.file.reveal.message = File {0} cannot be found
+
+# Alert file open error
+alert.error.file.open.title = File opening failed
```
Comment (jperedadnr) [inline kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit.properties:436]: do these need translation?

File: kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/editor/timeout.cmd [hunk 5]
```diff
@@ -0,0 +1,3 @@
+ECHO Waiting for 20sec
```
Comment (jperedadnr) [inline kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/editor/timeout.cmd:1]: 20 seconds or 5 seconds?

File: kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/editor/timeout.sh [hunk 6]
```diff
@@ -0,0 +1,3 @@
+echo Waiting for 20sec
```
Comment (jperedadnr) [inline kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/editor/timeout.sh:1]: same here

Comment (Oliver-Loeffler) [reply kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/editor/timeout.sh:1]: Corrected.

File: kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit.properties (hunk 4 above)
Comment (Oliver-Loeffler) [reply kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit.properties:436]: I think eventually yes, but at this very moment I am not actually capable to properly translate into japanese or chinese. Any good idea to achieve this automatically? One idea was to ask @ktgw0316 for the Japanese translation and possibly @weg2022 for the Chinese one.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorController.java (hunk 2 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorController.java]: done

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java [hunk 7]
```diff
@@ -68,6 +76,10 @@ public static OS get() {
 
     private static final String osName = System.getProperty("os.name").toLowerCase(Locale.ROOT); //NOI18N
 
+    static {
+        LOGGER.log(Level.INFO, "Detected Operating System: {0}", osName);
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java]: done

File: app/src/main/resources/com/oracle/javafx/scenebuilder/app/i18n/SceneBuilderApp.properties [hunk 8]
```diff
@@ -470,11 +468,29 @@ file.filter.label.image = Image Document
...
+error.file.open.details.title = File opening failed - Details 
 # {0} is a file path
 error.file.open.message = File {0} cannot be opened
-error.filesystem.details = Please check your file system.
-error.file.reveal.title = File locating failed
-error.file.reveal.message = File {0} cannot be found
+error.filesystem.details = File: {0}
+
+# File Reveal Error Dialog
+alert.error.file.reveal.title = Failed to reveal file ...
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply app/src/main/resources/com/oracle/javafx/scenebuilder/app/i18n/SceneBuilderApp.properties:477]: Good point, I'll add a new issue for the new properties. There is nie issue #734 .

File: app/src/main/java/com/oracle/javafx/scenebuilder/app/DocumentWindowController.java (hunk 1 above)
Comment (Oliver-Loeffler) [reply app/src/main/java/com/oracle/javafx/scenebuilder/app/DocumentWindowController.java:2334]: done

File: kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit.properties (hunk 4 above)
Comment (Oliver-Loeffler) [reply kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit.properties:436]: I've files issue #734 for this.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java (hunk 3 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java:384]: I  think it does run within JavaFX thread, as with my experiments with blocking tasks, the UI did actually freeze. After a quick test using `System.out.println("CURR THREAD: " + Thread.currentThread().getName());` it turned out, that it is indeed the JavaFX Application Thread.

To solve this, instead of using `Platform.runLater()` I would use a `Task` so we can collect any exceptions.
What do you thing @jperedadnr ?

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java [hunk 9]
```diff
@@ -331,54 +344,44 @@ public static void open(String path) throws IOException {
...
-                // Case Ubuntu 10.04 to 11.04: What you provide to nautilus is
-                // the name of the directory containing the file you want to see
-                // listed. See DTL-5384.
-                path = filePath.getAbsoluteFile().getParent();
-                if (path == null) {
-                    path = "."; //NOI18N
-                }
+            exitCodeOk = 1;
+        } else if (EditorPlatform.IS_LINUX) {           
+            args.add("xdg-open"); //NOI18N
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java:372]: I was consideriing testing if xdg is installed. However, that might work in different ways for different distributions. Having Nautilus as a backup might work but I think its not really desireable. There are many other file managers out there and `xdg-open` nicely delegates this task to the right point.

However, `xdg-open` is used to open all the documentation URLs, why should we not rely on this to open the file system view? Having a fallback included makes the code more complex without solving the actual problem. `xdg-open` was invented for this.

If we look for fallbacks, than we should not consider Nautilus or any other executable file manager, instead we should look into [alternatives to xdg-open](https://wiki.archlinux.org/title/Default_applications#Resource_openers).

I see multiple options.
* we could enhance the RPM package so, that it has a dependency to `xdg-utils`
* we could make the file manager call configurable in preferences, so that users can update it accordingly to their needs.
* add alternative resource openers on Linux to Scene Builder

My personal favourite would be an option to provide a custom command line call for this task (regardless if Mac, Windows or Linux). Windows is also bound to explorer despite nice alternative file managers such es FreeCommander or TotalCommander.

File: README.md [hunk 10]
```diff
@@ -20,6 +20,10 @@ See the [documentation](http://docs.gluonhq.com/scenebuilder/) about the new fea
 
 For community support, go to [StackOverflow](https://stackoverflow.com/questions/tagged/scenebuilder).
 
+### Requirements on Linux ###
+
+On Linux systems, Scene Builder uses the `xdg-open` to reveal files in the systems default file system browser or to open URLs in the default web browser. Most modern Linux Desktop Environments already provide the [xdg-utils](https://freedesktop.org/wiki/Software/xdg-utils/) package. If it is missing, it can be installed using the respective Linux package management tool such as `yum`, `apt-get`, `dnf` or `pacman`. The `xdg-utils` package is usually available on KDE based systems, some Arch based systems may require manual installations.
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply README.md]: Thanks, I've corrected that as well.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (jperedadnr) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java:374]: I'm fine removing nautilus, and now I see that `xdg-utils` is already installed in the linux workflow:
https://github.com/gluonhq/scenebuilder/blob/master/.github/workflows/bundles-linux.yml#L30

so I'm okay not having a fallback, but I'd like to show an error dialog if `xdg-utils` is not found nonetheless, instead of the current hidden exception when the command line fails.

As a follow-up, yes, we could add a custom command line call in preferences

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java [hunk 11]
```diff
@@ -331,54 +346,44 @@ public static void open(String path) throws IOException {
...
             }
             args.add(path);
         } else {
             // Not Supported
+            LOGGER.log(Level.SEVERE, "Unsupported operating system! Cannot reveal location {0} in file browser.", path);
         }
 
         if (!args.isEmpty()) {
-            executeDaemon(args, null);
+        	executeDaemon(args, null, exitCodeOk);
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java:386]: fix double indentation

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java [hunk 12]
```diff
@@ -410,18 +415,66 @@ public static boolean isNonContinousSelectKeyDown(MouseEvent e) {
...
-        try {
-            ProcessBuilder builder = new ProcessBuilder(cmd);
-            builder = builder.directory(wDir);
-            builder.start();
-        } catch (RuntimeException ex) {
-            throw new IOException(ex);
-        }
+    private static void executeDaemon(List<String> cmd, File wDir, int exitCodeOk) throws IOException, FileBrowserRevealException {
+    	Task<Void> cmdTask = new Task<Void>() {
+			@Override
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java:438]: fix indentation

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java [hunk 13]
```diff
@@ -410,18 +415,66 @@ public static boolean isNonContinousSelectKeyDown(MouseEvent e) {
...
+		        long timeoutSec = 5;
+		        try {
+		            int exitValue = new Cmd().exec(cmd, wDir, timeoutSec);
+		            if (exitCodeOk != exitValue) {
+		                LOGGER.log(Level.SEVERE, "Error during attempt to run: {0} in {1}", new Object[] {cmdLine, wDir});
+		                throw new FileBrowserRevealException(
+		                        "The command to reval the file exited with an error (exitValue=%s).\nCommand: %s\nWorking Dir: %s"
+		                        .formatted(Integer.toString(exitValue), cmdLine, wDir));
+		            } else {
+		                LOGGER.log(Level.INFO, "Successfully executed command: {0} in {1}", new Object[] {cmdLine, wDir});
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java:450]: FINE level

**Comment by Oliver-Loeffler** [comment]
@jperedadnr I will revert this so that the actual work is still performed in JavaFX application thread as before this change.
After reviewing the code and looking where possible changes have to be implemented, I thing filing another issue for refactoring is a better ider. Otherwise this PR becomes too large. It already touches quite many files.

Main purpose is to address the quality of the error messages and the use of `xdg-open` instead of `nautilus`.  The issue for the anyway required refactoring is #737.

**Review by jperedadnr — APPROVED** [review]
Looks good!
