### PR TITLE
Fix for issue #386

### LINKED ISSUE #386: FileSystemWatchService is never stopped and is spawned multiple times
The watchService for user library is never stopped and it is spawned twice or more.
I'm creating this issue as described in #236 
I'm going to do a PR for this shortly (I hope..)

### Expected Behavior
The watchService should be terminated gracefully

### Current Behavior
The watchService is never stopped

### Steps to Reproduce
Import a library from jar/fxml manager.
Drop that library.
Install again.
Drop again.
Install again.

image

You will have many threads named "FileSystemWatchService" doing the same job and not releasing resources.

image

### PR DESCRIPTION
**Pull request by mimmoz81**
This PR fixes #386.
FileSystemWatcherService is stopped on a finally block.

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
This is a simple change and looks OK to me. I would also like @jperedadnr to have a look a look at it before we go ahead and merge the same.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java [hunk 1]
```diff
@@ -161,98 +161,110 @@ private void runDiscovery() throws InterruptedException {
...
+                        } while (wk.reset());
+                    } catch(IOException x) {
+                        Thread.sleep(1000 /* ms */);
+                    }
                 }
-            }
 
+            }
+        }
+        finally {
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java:259]: Do you think it would make sense to move the `InterruptException` thrown from the method signature to a `catch` in the new  `try {} finally {}` ?
I don't think there is any difference, but it might help clarifying how the `while (true) {}` is terminated. It might also help adding a comment to that catch like:
```
// Ignored: Typically, when UserLibrary::stopWatching is invoked, an interruptionException is triggered to stop
// this watch service 
```
that would also help understanding why `finalize` is needed.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java [hunk 2]
```diff
@@ -161,98 +161,110 @@ private void runDiscovery() throws InterruptedException {
...
-
-            WatchService watchService = null;
-            while (watchService == null) {
-                try {
-                    watchService = folder.getFileSystem().newWatchService();
-                } catch(IOException x) {
-                    System.out.println("FileSystem.newWatchService() failed"); //NOI18N
-                    System.out.println("Sleeping..."); //NOI18N
-                    Thread.sleep(1000 /* ms */);
+        WatchService watchService = null;
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java:164]: Update copyright year in license header

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java (hunk 1 above)
Comment (mimmoz81) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java:259]: Well, there is already a catch at line 102 that catches both runDiscovery() and runWatching().
In my opinion it is better to leave both methods with the throws InterruptedException as they are and have a single catch clause that handles both. Infact an interrupt could happen just before runWatching() during runDiscovery().
Having a single catch block is better even if in the future there will be another runSomething() following runWatching()..
It is ok to better clarify with a comment atone 102 and, I add, to log at info level the end of the service/thread.

Comment (jperedadnr) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java:259]: That makes sense. Just maybe include the comment I suggested to the finally clause? No need to log at info level though.

Comment (mimmoz81) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java:259]: Ok I'll add the comment. I'm out for vacation these days. I will be back next monday.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java (hunk 2 above)
Comment (mimmoz81) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java:164]: Ok will do that

**Comment by mimmoz81** [comment]
@jperedadnr comments added and year updated

**Review by jperedadnr — APPROVED** [review]
Looks good
