### PR TITLE
test: Migrated existing tests to JUnit5 API - removed JUnit4 (2/2)

### LINKED ISSUE #449: Migrate from JUnit 4 to most recent JUnit 5.8+
The number of tests in Scene Builder is growing.
Many tests can be implemented as parametrized tests, also few tests require multiple assertions.

### Expected Behavior
* test frame work should be easy to use, support lambdas, parametrized tests, extensions etc.
* handling of exceptions

### Current Behavior
* Junit 4 as a very limited support for nice parametrized tests
* Cannot run multiple asserts (assert all)

### Context
* As one goal is now to grow the number of tests in Scene Builder, this is a chance to move to JUnit5 and make testing easier.

### PR DESCRIPTION
**Pull request by Oliver-Loeffler**
Contributes to effort to modernize test infrastructure.
All existing tests migrated to JUnit5 API.

This is the follow up to PR #478

### Issue

Fixes #449

### Progress

- [x] Change must not contain extraneous whitespace
- [x] License header year is updated, if required
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/DialogListItemComparatorTest.java [hunk 1]
```diff
@@ -32,21 +32,21 @@
...
+import static org.junit.jupiter.api.Assertions.assertTrue;
 
 import java.net.URL;
 import java.nio.file.Path;
 import java.nio.file.Paths;
 
-import org.junit.Test;
+import org.junit.jupiter.api.Test;
 
-public class DialogListItemComparatorTest {
```
Comment (AlmasB) [inline kit/src/test/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/DialogListItemComparatorTest.java:44]: Not sure about modifier change... does this affect anything syntactically, or is this preference based change? Without this change, the PR should be much easier to review.

File: pom.xml [hunk 2]
```diff
@@ -34,7 +36,48 @@
...
+            <artifactId>junit-jupiter-api</artifactId>
+            <scope>test</scope>
+        </dependency>
+        <dependency>
+            <groupId>org.junit.jupiter</groupId>
+            <artifactId>junit-jupiter-params</artifactId>
+            <scope>test</scope>
+        </dependency>
+        <dependency>
+            <groupId>junit</groupId>
```
Comment (AlmasB) [inline pom.xml:64]: I think we should just remove junit 4 and rework any dangling PRs.

File: pom.xml [hunk 3]
```diff
@@ -34,7 +36,48 @@
...
+            <scope>test</scope>
+        </dependency>
+        <dependency>
+            <groupId>org.junit.jupiter</groupId>
+            <artifactId>junit-jupiter-engine</artifactId>
+            <scope>test</scope>
+        </dependency>
+        <dependency>
+            <groupId>org.junit.vintage</groupId>
+            <artifactId>junit-vintage-engine</artifactId>
```
Comment (AlmasB) [inline pom.xml:76]: I don't think I've used vintage engine, is this for compatibility? If junit 4 goes, does this also go?

**Review by AlmasB — COMMENTED** [review]
Thanks for this, left some comments for discussion.

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/DialogListItemComparatorTest.java (hunk 1 above)
Comment (Oliver-Loeffler) [reply kit/src/test/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/DialogListItemComparatorTest.java:44]: I agree, so I've reverted changes to modifiers where possible.

File: pom.xml (hunk 2 above)
Comment (Oliver-Loeffler) [reply pom.xml]: Also agree here. So I've removed JUnit4 support.

File: pom.xml (hunk 3 above)
Comment (Oliver-Loeffler) [reply pom.xml]: Yes, Vintage engine was supposed to run the Junit4 tests. With Junit4 gone, this also goes away.

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisablerTest.java [hunk 4]
```diff
@@ -58,8 +58,8 @@ public void that_property_value_is_set_to_false_on_MacOS() throws Exception {
     public void that_property_value_is_not_modified_on_Windows() throws Exception {
         classUnderTest = new FXMLPropertiesDisabler(OS.WINDOWS);
         String fxmlText = readResourceText("ContainerWithMenuSystemMenuBarEnabled.fxml");
-        assertTrue("ensures that test resource is correct",
-                fxmlText.contains("<MenuBar useSystemMenuBar=\"true\" VBox.vgrow=\"NEVER\" fx:id=\"theMenuBar\">"));
+        assertTrue(fxmlText.contains("<MenuBar useSystemMenuBar=\"true\" VBox.vgrow=\"NEVER\" fx:id=\"theMenuBar\">"),
+                "ensures that test resource is correct");
```
Comment (Oliver-Loeffler) [inline kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisablerTest.java:62]: JUnit5 API has changed here, so that the test description is now the last method argument. In JUnit4 it was the first argument. This change applies to all assertX methods with a description.

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java [hunk 5]
```diff
@@ -91,40 +91,40 @@ public void that_FOR_PREVIEW_useSystemMenuBarProperty_is_enabled() throws Except
...
+                "for preview, useSystemMenu is expected to be enabled");
 
         String generatedFxml = classUnderTest.getFxmlText(false);
         assertTrue(generatedFxml.contains("useSystemMenuBar=\"true\""));
     }
 
     @Test
     public void that_useSystemMenuBarProperty_is_disabled_on_MacOS() throws Exception {
-        assumeTrue("MacOS", OS.get() == OS.MAC);
+        assumeTrue(OS.get() == OS.MAC, "MacOS");
```
Comment (Oliver-Loeffler) [inline kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java:103]: Same rules for descriptions applies to JUnit5 assumptions. A description is now always the last method argument.

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisablerVariationsTest.java [hunk 6]
```diff
@@ -31,64 +31,40 @@
...
-import org.junit.Test;
-import org.junit.runner.RunWith;
-import org.junit.runners.Parameterized;
-import org.junit.runners.Parameterized.Parameters;
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.CsvSource;
 
 import com.oracle.javafx.scenebuilder.kit.editor.EditorPlatform.OS;
 
-@RunWith(Parameterized.class)
```
Comment (Oliver-Loeffler) [inline kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisablerVariationsTest.java:46]: Junit5 handles parameterized tests in a very convenient way. No constructor for the test class is needed, also no specialized test runner. All you need is the `@ParameterizedTest` annotation and a value source where I've selected the `CsvCsvSource`. Another advantage is, that we now can place other tests for this class/area in the same test class. 
In Junit4, a seperate test class would have been required.

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonFileNameProposalTest.java [hunk 7]
```diff
@@ -107,11 +103,11 @@ public void that_fxmlLocation_in_resources_dir_is_changed_to_java_specific_direc
     }
 
     @Test
-    public void that_fxmlLocation_in_resources_dir_is_changed_to_kotlin_specific_directory() throws Exception {
+    public void that_fxmlLocation_in_resources_dir_is_changed_to_kotlin_specific_directory(@TempDir Path temporaryDirectory) throws Exception {
```
Comment (Oliver-Loeffler) [inline kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonFileNameProposalTest.java:106]: JUnit5 `@TempDir` is awesome, you can use it at any place where it is needed. It is no longer necessary to make it a field of the test class. It works fine as a method argument.

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/DialogListItemComparatorTest.java (hunk 1 above)
Comment (Oliver-Loeffler) [reply kit/src/test/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/DialogListItemComparatorTest.java:44]: Well, in JUnit4 it was mandatory to make test classes and test methods public. This is no longer necessary for JUnit5, here package visibility will be enough (with exceptions such as when you use methods in a static context e.g. with `@BeforeAll` annotation). So changing test class visibility to package/default can be a 3rd PR.

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java [hunk 8]
```diff
@@ -91,40 +91,40 @@ public void that_FOR_PREVIEW_useSystemMenuBarProperty_is_enabled() throws Except
...
+                "for preview, useSystemMenu is expected to be enabled");
 
         String generatedFxml = classUnderTest.getFxmlText(false);
         assertTrue(generatedFxml.contains("useSystemMenuBar=\"true\""));
     }
 
     @Test
     public void that_useSystemMenuBarProperty_not_modified_on_Linux_and_Windows() throws Exception {
-        assumeTrue("Windows or Linux", Set.of(OS.LINUX, OS.WINDOWS).contains(OS.get()));
+        assumeTrue(Set.of(OS.LINUX, OS.WINDOWS).contains(OS.get()), "Windows or Linux");
```
Comment (AlmasB) [inline kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java:119]: Perhaps adding [disabled on os](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/condition/DisabledOnOs.html) or enabled on os would be clearer?

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java [hunk 9]
```diff
@@ -91,40 +91,40 @@ public void that_FOR_PREVIEW_useSystemMenuBarProperty_is_enabled() throws Except
...
+        assertTrue(((MenuBar) fxomObject.getSceneGraphObject()).useSystemMenuBarProperty().get(),
+                "for preview, useSystemMenu is expected to be enabled");
 
         String generatedFxml = classUnderTest.getFxmlText(false);
         assertTrue(generatedFxml.contains("useSystemMenuBar=\"true\""));
     }
 
     @Test
     public void that_useSystemMenuBarProperty_is_disabled_on_MacOS() throws Exception {
-        assumeTrue("MacOS", OS.get() == OS.MAC);
```
Comment (AlmasB) [inline kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java:103]: Perhaps adding [disabled on os](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/condition/DisabledOnOs.html) or enabled on os would be clearer?

**Review by AlmasB — COMMENTED** [review]
Looks good. I assume all tests (after this PR) are JUnit 5 only?

Also please check the comments.

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java (hunk 8 above)
Comment (Oliver-Loeffler) [reply kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java:119]: Yes, very good idea. Much better than this.

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java (hunk 9 above)
Comment (Oliver-Loeffler) [reply kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java:103]: Agree.

Comment (Oliver-Loeffler) [reply kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java:103]: JUnit4 will no longer work.

**Review by AlmasB — APPROVED** [review]
