### PR TITLE
fix: getLatestVersion runs now as JavaFX task in JavaFX thread 

### LINKED ISSUE #601: CheckUpdate functionality runs in wrong thread at the first call after app starts
When SceneBuilder is started first time and the the function `Menu -> Help\Check for update,,,` is called, there will be no dialog to indicate any action. Instead a stack trace like the following is produced.

The issue does not occur for repeated calls to `SceneBuilderApp.checkUpdates()` method.

```
Nov. 08, 2022 6:27:46 PM com.oracle.javafx.scenebuilder.app.SceneBuilderApp$SceneBuilderUncaughtExceptionHandler uncaughtException
SCHWERWIEGEND: An exception was thrown:
java.lang.IllegalStateException: Not on FX application thread; currentThread = GetLatestVersion
        at javafx.graphics@19/com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:299)
        at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:458)
        at javafx.graphics@19/javafx.stage.Stage.<init>(Stage.java:258)
        at javafx.graphics@19/javafx.stage.Stage.<init>(Stage.java:244)
        at javafx.controls@19/javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
        at javafx.controls@19/javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
        at javafx.controls@19/javafx.scene.control.Dialog.<init>(Dialog.java:252)
        at javafx.controls@19/javafx.scene.control.Alert.<init>(Alert.java:247)
        at javafx.controls@19/javafx.scene.control.Alert.<init>(Alert.java:222)
        at com.oracle.javafx.scenebuilder.kit.alert.SBAlert.<init>(SBAlert.java:43)
        at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.lambda$checkUpdates$20(SceneBuilderApp.java:1055)
        at com.oracle.javafx.scenebuilder.app.util.AppSettings.lambda$getLatestVersion$0(AppSettings.java:141)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected Behavior
* With a click on `Help\Check for update,,,`, SceneBuilder is expected to respond to the user

### Current Behavior
* With a click on `Help\Check for update,,,`, SceneBuilder does not show the requested dialog, instead an exception is thrown.
* With a repeated click on `Help\Check for update,,,` the expected dialog appears and no exception is thrown

### Steps to Reproduce
* on Windows 10:
    * clone Scene Builder
    * run the build
    * run the app
    * open any FXML or start over with empty template
    * Run: `Help\Check for update,,,`

### Your Environment
* Win10 21H2, Java 19, JavaFX 19, 
* Started with Maven on Windows Command Line

### PR DESCRIPTION
**Pull request by Oliver-Loeffler**
The getLatestVersion action failed in some cases, especially and repeatably direct after Scene Builder start.
This caused the update dialog to not show upon request from help menu.

### Issue

Fixes #601 

### Progress

- [x] Change must not contain extraneous whitespace
- [x] License header year is updated, if required
- [x] The PR name must follow the [pre-defined format](https://github.com/gluonhq/scenebuilder/blob/master/CONTRIBUTING.md)
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

File: app/src/main/java/com/oracle/javafx/scenebuilder/app/util/AppSettings.java [hunk 1]
```diff
@@ -117,32 +122,46 @@ public static boolean isCurrentVersionLowerThan(String version) {
...
-            consumer.accept(latestVersion);
-        }
+                return onlineVersionNumber;
+            }
+
+            protected void succeeded() { 
+                String fetchedVersion = getValue();
+                LOGGER.log(Level.INFO, "Latest online available version is: {0}", fetchedVersion);
+                consumer.accept(fetchedVersion);
+                latestVersion = fetchedVersion;
```
Comment (Oliver-Loeffler) [inline app/src/main/java/com/oracle/javafx/scenebuilder/app/util/AppSettings.java:162]: The `latestVersion` is now populated as before.
