### PR TITLE
Load logging configuration in Application class

### LINKED ISSUE #370: Log files are not created
The About dialog mentions that the log file must be created in tmp directory. However, no log files are created.

This is because no log file config is loaded by Scene Builder.

### Expected Behavior

Log file should be generated when Scene Builder runs.

### Current Behavior

No log files are generated

### Steps to Reproduce

Run Scene Builder on any platform and no log files are created.

### PR DESCRIPTION
**Pull request by abhinayagarwal**
### Issue

Fixes #370 

### Progress

- [x] Change must not contain extraneous whitespace
- [x] License header year is updated, if required
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

File: app/src/main/resources/logging.properties [hunk 1]
```diff
@@ -0,0 +1,7 @@
+handlers= java.util.logging.FileHandler
+
+# File Logging
+java.util.logging.FileHandler.pattern = ${java.io.tmpdir}/scenebuilder-${version}.log
```
Comment (jperedadnr) [inline app/src/main/resources/logging.properties:4]: Probably better to log to `~/.scenebuilder` (and change the message on the dialog)? It would be more permanent.

**Comment by palexdev** [comment]
Yay finally, with this we can probably investigate further Issue #354 (Updated with video)

File: app/src/main/resources/logging.properties [hunk 2]
```diff
@@ -0,0 +1,7 @@
+handlers= java.util.logging.FileHandler
+
+# File Logging
+java.util.logging.FileHandler.pattern = %h/.scenebuilder/logs/scenebuilder-${version}.log
```
Comment (jperedadnr) [inline app/src/main/resources/logging.properties:4]: this fails on Mac:
```
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: /Users/JosePereda/.scenebuilder/logs/scenebuilder-16.0.0-SNAPSHOT.log.lck
```

If you check AppPlatform, the app folder is not `~/.scenebuilder` for all platforms.

Comment (abhinayagarwal) [reply app/src/main/resources/logging.properties:4]: I now see that the [Application Data directory](https://github.com/gluonhq/scenebuilder/blob/master/app/src/main/java/com/oracle/javafx/scenebuilder/app/AppPlatform.java#L64) is different for different platforms. I wonder why was it done instead of using `${user.home}/.scenebuilder`?

Comment (jperedadnr) [reply app/src/main/resources/logging.properties:4]: Can't reply to that :) 
If needed for logs only you might want to simply use `${user.home}/.scenebuilder` for all platforms?

File: app/src/main/java/com/oracle/javafx/scenebuilder/app/AppPlatform.java [hunk 3]
```diff
@@ -90,6 +91,17 @@ public static synchronized String getUserLibraryFolder() {
         return userLibraryFolder;
     }
 
+    /**
+     * Returns the directory path for logs. Default path is "${user.home}/.scenebuilder/logs/".
+     * @return Directory path for Scene Builder logs
+     */
+    public static synchronized String getLogFolder() {
+        if (logsFolder == null) {
+            logsFolder = System.getProperty("user.home") + "/.scenebuilder/logs"; //NOI18N
```
Comment (jperedadnr) [inline app/src/main/java/com/oracle/javafx/scenebuilder/app/AppPlatform.java:100]: Does this work on Windows? `File.separator` is probably needed

File: app/src/main/resources/logging.properties [hunk 4]
```diff
@@ -0,0 +1,7 @@
...
+java.util.logging.FileHandler.count = 1
```
Comment (jperedadnr) [inline app/src/main/resources/logging.properties:5]: I see that the log is restarted whenever you stop and start a new instance of Scene Builder, removing the previous logs.
Should we just have a rolling system with a maximum number of files (like 10), and size per file (like 1 MB), but keep everything until the limit is reached?

**Review by jperedadnr — APPROVED** [review]

**Comment by credmond** [comment]
Hi @abhinayagarwal, this change introduced a bug whereby no logging file ever gets created when SceneBuilder was ran from a JAR. I have fixed this here:

https://github.com/gluonhq/scenebuilder/pull/658

... given the amount if bugs in SceneBuilder, I think logging is a priority. Can we get this into the next release please? Reproducing is easy, just run SceneBuilder from a JAR or from the packaged SceneBuilder.exe.
