### PR TITLE
MacOS: avoid hiding SceneBuilder menu bar with FXML menu bar when useSystemMenuBar property is enabled

### LINKED ISSUE #404: Scenebuilder on MacOS does not display menu
Scenebuilder on MacOS does not show menu when FXML file has useMenuSystemBar set to true in the FXML file loaded into SceneBuilder..

### Expected Behavior
SceneBuilder should show its full menu no matter what the FXML file being edited contains.

### Current Behavior
SceneBuilder shows the menu from the FXML file.

### Steps to Reproduce
Run SceneBuilder on macOS and load an FXML file that contains something like:
<MenuBar useSystemMenuBar="true" BorderPane.alignment="CENTER">

### Your Environment
Product Version
JavaFX Scene Builder 16.0.0

Build Information
Version 16.0.0
Date: 2021-03-26 18:42:37
JavaFX Version: 16
Java Version: 16+36, AdoptOpenJDK

Logging
The default configuration stores logging output in a file named scenebuilder-16.0.0.log (possibly followed by a trailing '.' and a digit).
The default file path is /var/folders/6x/pg8zpv0s1jj6vnpxn028g7dc0000gn/T/scenebuilder-16.0.0.log

JavaFX
16

Java
16+36, AdoptOpenJDK

Operating System
Mac OS X, x86_64, 10.16

### Screenshots

Screenshot 2021-09-04 at 09 55 24

### PR DESCRIPTION
**Pull request by Oliver-Loeffler**
For MacOS, when Scene Builder opens a FXML file with a MenuBar with property `useSystemMenuBar="true"`,
then the SceneBuilder menu bar is replaced with the menu bar defined in FXML. Hence SceneBuilder becomes impossible to use.

This PR introduces code which conditionally disables the `useSystemMenuBar="true"` in the constructor of `com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument`. As there was already a boolean parameter `normalized`, the boolean arguments have been replaced with an enum type `FXOMDocumentSwitch` which provides the values `NON_NORMALIZED` and `FOR_PREVIEW`. The change of internal API is minimal and there is no change in default behavior of the `FXOMDocument` constructor.

**Default behavior**
For normal loading of an FXML file using the `FXOMDocument` constructor, the FXML text which is supplied to the FXMLLoader is modified, so that value of `useSystemMenuBar` is turned to `false`. This change is not reflected in the FXOM so that the original setting is preserved and can be saved to an FXML file again. 
Thus, when loading an accordingly modified FXML file, the SceneBuilder menu will remain the one displayed in MacOS menu bar.
An prepared example is provided within the test resources. `kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/ContainerWithMenu_SystemMenuBarEnabled.fxml`

**Preview behavior**
For previews instead, it migh be desirable to have exactly the behavior that the menu from a given FXML is displayed in MacOS menu bar. Therefore, the argument `FXOMDocumentSwitch.FOR_PREVIEW` is added to the call of the `FXOMDocument` constructor in `com.oracle.javafx.scenebuilder.kit.preview.PreviewWindowController`. In that case, the FXML text which is supplied to the FXMLLoader is not modified at all and if the property `useSystemMenuBar="true"` exists, then the menubar defined in preview will be displayed in MacOS menu bar.

### Issue 

Fixes #404

### Progress

- [x] Change must not contain extraneous whitespace
- [x] License header year is updated, if required
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMLoader.java [hunk 1]
```diff
@@ -287,7 +287,7 @@ public void readPropertyAttribute(String name, Class<?> staticClass, String fxml
         } else if (currentTransientNode instanceof TransientProperty) {
             final TransientProperty transientProperty = (TransientProperty) currentTransientNode;
             transientProperty.getCollectedProperties().add(fxomProperty);
-        } else if(currentTransientNode instanceof  TransientIntrinsic) {
+        } else if(currentTransientNode instanceof TransientIntrinsic) {
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMLoader.java:290]: since you are at it, `else if (`

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+     * editing must happen before loading the FXML using the FXMLLoader.
+     * 
+     * Here a disconnect between the FXOM and FXML is created as the state of the
+     * useSystemMenuBarProperty is now different in both models.
+     * 
+     * @param fxmlText FXML source to be modified
+     * @return FXML source with all properties disabled (=false) where WYSIWYG editing is not suitable.
+     * 
+     */
+    public String disableUseSystemMenuBarProperty(String fxmlText) {
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:56]: You have created a class to disable some properties if needed. Not sure how many more methods are we going to add here, but it is probably better to have a public API like `disableProperties(String fxmlText)`, that will internally call all the private methods that we have or add in the future, like `disableUseSystemMenuBarProperty` (see [normalize()](https://github.com/gluonhq/scenebuilder/blob/master/kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMNormalizer.java#L105) for instance).

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java [hunk 3]
```diff
@@ -80,16 +81,23 @@
     
     private List<Class<?>> initialDeclaredClasses;
     
-    public FXOMDocument(String fxmlText, URL location, ClassLoader classLoader, ResourceBundle resources, boolean normalize) throws IOException {
+    public FXOMDocument(String fxmlText, URL location, ClassLoader classLoader, ResourceBundle resources, FXOMDocumentSwitch... switches) throws IOException {
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:84]: Add JavaDoc to this method

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+        return fxmlText.replace("useSystemMenuBar=\"true\"",
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:57]: I agree with the null check. Not sure with the platform check, would leave that out as probably other platforms will have that once a while. The more I think about that topic, also having in mind the issue related to the user data (#253), I propose to rename that class to `FXMLTextPreprocessor` and than make the behavior platform dependent.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMLoader.java (hunk 1 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMLoader.java:290]: Okay.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java (hunk 2 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:56]: Yes, I fully agree with that and I already see some future use especially with #253.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java (hunk 3 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:84]: Okay.

**Comment by abhinayagarwal** [comment]
Hi @Oliver-Loeffler ,

Do you plan to work on this PR and resolve Jose's comments?

**Comment by Oliver-Loeffler** [comment]
Yes for sure - will see to make some progress here during next days.

**Comment by Oliver-Loeffler** [comment]
Hi @abhinayagarwal & @jperedadnr,
it took a while but eventually I was able to put some more work in this. Thanks for your feedback so far - looking forward to your remarks & advice.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java [hunk 5]
```diff
@@ -443,4 +457,25 @@ public SceneGraphHolder getSceneGraphHolder() {
         public void fxomDocumentWillRefreshSceneGraph(FXOMDocument fxomDocument);
         public void fxomDocumentDidRefreshSceneGraph(FXOMDocument fxomDocument);
     }
+    
+    /**
+     * Depending on where the {@link FXOMDocument} shall be used, 
+     * it is necessary to configure the {@link FXOMDocument} creation process.
+     * The switches here can be used to configure the creation process in the desired way.
+     * This enum replaces the previously used boolean arguments in the {@link FXOMDocument} constructor.
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:465]: This line `"This enum..."` can be removed?

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java [hunk 6]
```diff
@@ -0,0 +1,111 @@
...
+ * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+ * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+ */
+package com.oracle.javafx.scenebuilder.kit.fxom;
+
+import java.util.Locale;
+import java.util.Objects;
+
+class FXMLPropertiesDisabler {
+    private final OperatingSystem os;
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:38]: Add blank lines after this field and after each method

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+    private String disableUseSystemMenuBarProperty(String fxmlText) {
+        Objects.requireNonNull(fxmlText, "fxmlText must not be null");
+        if (OperatingSystem.MACOS.equals(os)) {
+            return fxmlText.replace("useSystemMenuBar=\"true\"",
+                                    "useSystemMenuBar=\"false\"");
+        }
+        return fxmlText;
+    }
+    
+    enum OperatingSystem {
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:87]: `com.oracle.javafx.scenebuilder.kit.editor.EditorPlatform` already contains `IS_MAC`, so this private enum is not required at all.

Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:87]: `com.oracle.javafx.scenebuilder.kit.editor.EditorPlatform` already contains `IS_MAC`, so this private enum is not required at all.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java [hunk 8]
```diff
@@ -443,4 +457,25 @@ public SceneGraphHolder getSceneGraphHolder() {
...
+     */
+    public enum FXOMDocumentSwitch {
+        /**
+         * If this switch is defined, the {@link FXOMDocument} will not be normalized (see {@link FXOMNormalizer}).
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:469]: Reword:
```
When this flag is present, the {@link FXOMDocument} will not be normalized (see {@link FXOMNormalizer})
```

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java [hunk 9]
```diff
@@ -443,4 +457,25 @@ public SceneGraphHolder getSceneGraphHolder() {
...
+         */
+        NON_NORMALIZED,
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:471]: Before this PR, a boolean was used,  `normalize`. I don't see why you use the opposite enum `NON_NORMALIZED`, and then negate it `if !NON_NORMALIZED`. 

Maybe it is better to define both `NORMALIZED` and `NON_NORMALIZED`?

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java [hunk 10]
```diff
@@ -443,4 +457,25 @@ public SceneGraphHolder getSceneGraphHolder() {
...
+        
+        /**
+         * When this flag is present during {@link FXOMDocument} creation,
+         * the {@link FXMLPropertiesDisabler} will be used to prepare the FXML source in a way, 
+         * so that settings defined in the FXML will not interfere Scene Builders configuration.
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:476]:
```
* the {@link FXMLPropertiesDisabler} will be used to modify the FXML source in such a way
* that the included settings will not interfere Scene Builder's configuration.
```

Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:476]:
```
* the {@link FXMLPropertiesDisabler} will be used to modify the FXML source in such a way
* that the included settings will not interfere Scene Builder's configuration.
```

**Comment by Oliver-Loeffler** [comment]
Hi @jperedadnr,
I will rework the way how the enum works and how the constants are named. That one is called `NON_NORMALIZED` is just a result from the refactoring as previously I only found one location where the normalize boolean was true, so `NORMALIZED` was the default. I was considering to revert it to NORMALIZED but was hesitating as it were more changes than actually wanted. However, I agree with calling it NORMALIZED, it is then much clearer.

For the `OperatingSystem` enum, it's just there to make testing easier and to avoid playing around with all these boolean flags. I'd even propose to delegate the behavior of EditorPlatform to the enum and make it public. I've stumbled over various places now where the code deals with platform specific and always using `EditorPlatform` for this would limit test execution to the target platform. What do you think? See PR #396 for instance.

**Comment by Oliver-Loeffler** [comment]
The Operating System enum is now removed, instead the call to `EditorPlatform.IS_MAC` is used to decide if a certain behavior is needed.

The enum item `NON_NORMALIZED` has been removed, a new item `NORMALIZED` has been added. Hence the default behavior of the `FXOMDocument` constructor changed, normalization is no longer the default. Now normalization must be enabled using the `NORMALIZED` switch.

**Review by jperedadnr — COMMENTED** [review]
A few more comments.
Maybe for a follow-up: there is no `useSystemMenuBar` field for `MenuBar`. Maybe we could add the required metadata, and show/enable it for Mac? I've already tested this PR with that, and preview works really well.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java [hunk 11]
```diff
@@ -0,0 +1,60 @@
...
+ * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+ * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+ * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+ */
+package com.oracle.javafx.scenebuilder.kit.fxom;
+
+class FXMLPropertiesDisabler {
+
+    /**
+     *
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:54]: Very good idea, I have prepared something very similar in PR #396.
But now, where we have the nice OS enum, I'd go s slightly different way. Instead of providing the condition as a constructor argument, I'd pass in the OS instead. The FXMLPropertiesDisabler can then act according to what is required by OS or platform. Such as:

```java
private final OS os;

    /**
     * @param os Operating system where Scene Builder is executed
     */
    public FXMLPropertiesDisabler(OS os) {
        this.os = Objects.requireNonNull(os);
    }
```

When the class is used, it should be constructed like that:

```java
  new FXMLPropertiesDisabler(OS.get());
  new FXMLPropertiesDisabler();  // this could be the default constrcutor where OS.get() is used in
```

And for the test:

```java
new FXMLPropertiesDisabler(OS.MAC);
new FXMLPropertiesDisabler(OS.WINDOWS);
new FXMLPropertiesDisabler(OS.LINUX);
...
```

What do you think?

[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:54]: I limited the scope of the first occurrence of the OS enum in this PR as I thought its too much of a change.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMIntrinsic.java [hunk 12]
```diff
@@ -57,7 +57,8 @@
     private Object sourceSceneGraphObject;
 
     
-    FXOMIntrinsic(FXOMDocument document, GlueElement glueElement, Object targetSceneGraphObject,  List<FXOMProperty> properties) {
+    FXOMIntrinsic(FXOMDocument document, GlueElement glueElement, Object targetSceneGraphObject,
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMIntrinsic.java:60]: Okay, good to know, didn't update it because this change is formatting only (following Checkstyle advice). Good to know, I will consider this for future commits.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMLoader.java [hunk 13]
```diff
@@ -312,7 +312,7 @@ public void readPropertyAttribute(String name, Class<?> staticClass, String fxml
         } else if (currentTransientNode instanceof TransientProperty) {
             final TransientProperty transientProperty = (TransientProperty) currentTransientNode;
             transientProperty.getCollectedProperties().add(fxomProperty);
-        } else if(currentTransientNode instanceof  TransientIntrinsic) {
+        } else if (currentTransientNode instanceof TransientIntrinsic) {
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMLoader.java:315]: Shall I revert those changes? For future PRs I'll definitely separate between formatting/refactoring and feature work.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java [hunk 14]
```diff
@@ -0,0 +1,92 @@
...
+     * useSystemMenuBarProperty is now different in both models.
+     * 
+     * @param fxmlText FXML source to be modified
+     * @return FXML source with all properties disabled (=false) where WYSIWYG editing is not suitable.
+     * @throws NullPointerException in case of fxmlText is null
+     */
+    private String disableUseSystemMenuBarProperty(String fxmlText) {
+        Objects.requireNonNull(fxmlText, "fxmlText must not be null");
+        if (isMacOS) {
+            return fxmlText.replace("useSystemMenuBar=\"true\"",
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:97]: Yes, there is an example file `kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/ContainerWithMenu_SystemMenuBarEnabled.fxml` for test. 

Exactly this line is tested, on MacOS and Linux/Windows?

Can you please elaborate?

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMLoader.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMLoader.java]: I have reverted this. Will keep it in mind for future.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMNodes.java [hunk 15]
```diff
@@ -720,7 +720,7 @@ private static FXOMDocument makeFxomDocumentFromImageURL(
             fitWidth = 0;
             fitHeight = 0;
         } else {
-            final double widthScale  = fitSize / imageSize;
+            final double widthScale = fitSize / imageSize;
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMNodes.java:723]: done

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMRefresher.java [hunk 16]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2019, Gluon and/or its affiliates.
+ * Copyright (c) 2019, 2021, Gluon and/or its affiliates.
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMRefresher.java]: done

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/preview/PreviewWindowController.java [hunk 17]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2016, 2019, Gluon and/or its affiliates.
+ * Copyright (c) 2016, 2019, 2021, Gluon and/or its affiliates.
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/preview/PreviewWindowController.java]: done

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java [hunk 18]
```diff
@@ -1,5 +1,6 @@
 /*
- * Copyright (c) 2022, Gluon and/or its affiliates.
+<<<<<<< HEAD
```
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocumentTest.java]: fixed this one

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (jperedadnr) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:97]: Sorry, mind the spaces before and/or after the `=`

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (jperedadnr) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:64]: A Predicate is more flexible, but so far she only use the OS itself, good enough for now.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:97]: This is a very good point for manually crafted FXMLs, I will add a more safe way to catch this. Thanks!
Do you have any good idea where to dig into when we want to enable editing this property in Scene Builder? By now, I was reading through the `InspectorPanelController` code but have not yet a good picture what we need to do.

[the remark this answers is not in the document]
Comment (jperedadnr) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:97]: I already gave you a hint: `metadata` :)
Check: `com.oracle.javafx.scenebuilder.kit.metadata.Metadata`, and then define a property `useSystemMenuBarName`, then valuePropertyMetadata `useSystemMenuBarNamePropertyMetadata` with it, and add it to `MenuBarMetadata.getProperties()`.

[the remark this answers is not in the document]
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java]: Thanks. The property replacement is now reworked. It uses now a regular expression. A parameterized test has been added as well to verify multiple cases.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java [hunk 19]
```diff
@@ -55,6 +55,14 @@
  * @treatAsPrivate
  */
 public class EditorPlatform {
+
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java:58]: update copyright year

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java [hunk 20]
```diff
@@ -0,0 +1,111 @@
...
+class FXMLPropertiesDisabler {
+
+    private final OS os;
+
+    /**
+     * Creates a new FXMLPropertiesDisable which is aware of the platform and can
+     * according to required platform behavior.
+     */
+    public FXMLPropertiesDisabler() {
+        this.os = OS.get();
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:51]: `this(OS.get())`?

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java [hunk 21]
```diff
@@ -4470,7 +4472,12 @@ public boolean isPropertyTrimmingNeeded(PropertyName name) {
                 com.oracle.javafx.scenebuilder.kit.metadata.property.value.DoublePropertyMetadata.DoubleKind.COORDINATE,
                 true, /* readWrite */
                 100.0, /* defaultValue */
-                new InspectorPath("Properties", "Specific", 98));
+                new InspectorPath("Properties", "Specific", 10));
+    private final ValuePropertyMetadata useSystemMenuBarNamePropertyMetadata =
+            new BooleanPropertyMetadata(useSystemMenuBarName, 
+                    true, /* readWrite */
+                    false, 
+                    new InspectorPath("Properties", "Specific", 70));
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java:4480]: Change `Specific` to `Node`, value can be 25 or so.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java [hunk 22]
```diff
@@ -4470,7 +4472,12 @@ public boolean isPropertyTrimmingNeeded(PropertyName name) {
                 com.oracle.javafx.scenebuilder.kit.metadata.property.value.DoublePropertyMetadata.DoubleKind.COORDINATE,
                 true, /* readWrite */
                 100.0, /* defaultValue */
-                new InspectorPath("Properties", "Specific", 98));
+                new InspectorPath("Properties", "Specific", 10));
+    private final ValuePropertyMetadata useSystemMenuBarNamePropertyMetadata =
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java:4476]: Rename `useSystemMenuBarNamePropertyMetadata` to `useSystemMenuBarPropertyMetadata`

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java [hunk 23]
```diff
@@ -5412,6 +5419,7 @@ private Metadata() {
         MenuBarMetadata.getProperties().add(accessibleRole_MENU_BAR_PropertyMetadata);
         MenuBarMetadata.getProperties().add(menusPropertyMetadata);
         MenuBarMetadata.getProperties().add(styleClass_c18_PropertyMetadata);
+        MenuBarMetadata.getProperties().add(useSystemMenuBarNamePropertyMetadata);
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java:5422]: `systemMenuBar` is added to `hiddenProperties` below. Probably you need to remove that.

File: kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisablerVariationsTest.java [hunk 24]
```diff
@@ -0,0 +1,97 @@
...
+                 { "5", "WINDOWS","<MenuBar    useSystemMenuBar  =  \"true\"\\t fx:id=\"theMenuBar\">",
+                                  "<MenuBar    useSystemMenuBar  =  \"true\"\\t fx:id=\"theMenuBar\">"},
+                 
+                 { "6", "LINUX",  "<MenuBar    useSystemMenuBar  =  \"true\"\\t fx:id=\"theMenuBar\">",
+                                  "<MenuBar    useSystemMenuBar  =  \"true\"\\t fx:id=\"theMenuBar\">"},
+           });
+    }
+
+    private String id;
+
```
Comment (jperedadnr) [inline kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisablerVariationsTest.java:77]: Minor, remove these empty lines between fields.

File: kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/ContainerWithMenu_SystemMenuBarEnabled.fxml [hunk 25]
```diff
@@ -0,0 +1,33 @@
+<?xml version="1.0" encoding="UTF-8"?>
```
Comment (jperedadnr) [inline kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/ContainerWithMenu_SystemMenuBarEnabled.fxml:1]: Minor, avoid underscores in file names

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java (hunk 19 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java:58]: updated

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java (hunk 21 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java]: Is there a guideline how to assign these properties correctly?

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java (hunk 23 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java]: It's been removed. Interestingly it worked even without removing it.

File: kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/ContainerWithMenu_SystemMenuBarEnabled.fxml (hunk 25 above)
Comment (Oliver-Loeffler) [reply kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/ContainerWithMenu_SystemMenuBarEnabled.fxml]: I've changed it to camel case.

**Comment by Oliver-Loeffler** [comment]
@jperedadnr Many thanks for your patience in this!

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java [hunk 26]
```diff
@@ -0,0 +1,111 @@
...
+/**
+ * Modifies FXML to be loaded so that properties in the FXML will not interfere
+ * with Scene Builder.
+ */
+class FXMLPropertiesDisabler {
+
+    private final OS os;
+
+    /**
+     * Creates a new FXMLPropertiesDisable which is aware of the platform and can
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:47]: "and can" ... ? you are missing something

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java [hunk 27]
```diff
@@ -0,0 +1,111 @@
...
+     * according to required platform behavior.
+     */
+    public FXMLPropertiesDisabler() {
+        this(OS.get());
+    }
+
+    /**
+     * @param os Operating system where Scene Builder is executed
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java:55]: not exactly: OS by default is where SB is running, but can be any other OS.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java [hunk 28]
```diff
@@ -102,13 +125,7 @@ public FXOMDocument(String fxmlText, URL location, ClassLoader classLoader, Reso
 
         hasGluonControls = fxmlText.contains(EditorPlatform.GLUON_PACKAGE);
     }
-    
-    
-    public FXOMDocument(String fxmlText, URL location, ClassLoader classLoader, ResourceBundle resources) throws IOException {
-        this(fxmlText, location, classLoader, resources, true /* normalize */);
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:108]: Hmm, I realize now that you have changed the default behaviour of all classed that called `FXOMDocument` via this removed constructor, where `normalize` was set to true: since they don't use switches now (except PreviewWindowController), therefore `normalized` is set to false but it used to be true. Only exception that works is FXOMRefresher (as it used the other constructor).

The only possible fix I see now is to add NORMALIZED to: EditorControler, AddContextMenuToSelectionJob, AddTootiplToSelectionJob, ImportWindowController,...

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMIntrinsic.java [hunk 29]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2012, 2014, Oracle and/or its affiliates.
+ * Copyright (c) 2012, 2022, Oracle and/or its affiliates.
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMIntrinsic.java:2]: To keep the scope of the PR (which is already complex enough), please undo the changes in classes that only affect formatting.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMNodes.java [hunk 30]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2012, 2014, Oracle and/or its affiliates.
+ * Copyright (c) 2012, 2022, Oracle and/or its affiliates.
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMNodes.java:2]: undo changes

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMObject.java [hunk 31]
```diff
@@ -289,14 +289,12 @@ public void moveBeforeSibling(FXOMObject sibling) {
     
     public Scene getScene() {
         final Scene result;
-
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMObject.java:292]: undo changes

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java [hunk 32]
```diff
@@ -4470,7 +4472,12 @@ public boolean isPropertyTrimmingNeeded(PropertyName name) {
                 com.oracle.javafx.scenebuilder.kit.metadata.property.value.DoublePropertyMetadata.DoubleKind.COORDINATE,
                 true, /* readWrite */
                 100.0, /* defaultValue */
-                new InspectorPath("Properties", "Specific", 98));
+                new InspectorPath("Properties", "Specific", 10));
+    private final ValuePropertyMetadata useSystemMenuBarPropertyMetadata =
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java:4476]: Have you tested this on Windows or Linux? The property is public API, so it shouldn't have any effect.

File: kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/NonNormalized_Accordion.fxml [hunk 33]
```diff
@@ -0,0 +1,27 @@
+<?xml version="1.0" encoding="UTF-8"?>
```
Comment (jperedadnr) [inline kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/NonNormalized_Accordion.fxml:1]: avoid underscore

File: kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/Normalized_Accordion.fxml [hunk 34]
```diff
@@ -0,0 +1,24 @@
+<?xml version="1.0" encoding="UTF-8"?>
```
Comment (jperedadnr) [inline kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/Normalized_Accordion.fxml:1]: Avoid underscore

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java [hunk 35]
```diff
@@ -4470,7 +4472,12 @@ public boolean isPropertyTrimmingNeeded(PropertyName name) {
                 com.oracle.javafx.scenebuilder.kit.metadata.property.value.DoublePropertyMetadata.DoubleKind.COORDINATE,
                 true, /* readWrite */
                 100.0, /* defaultValue */
-                new InspectorPath("Properties", "Specific", 98));
+                new InspectorPath("Properties", "Specific", 10));
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java:4475]: Why did you change 98 here?

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java (hunk 21 above)
Comment (jperedadnr) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java]: Not really. Most of SB features are undocumented, and fixing that is going to require a huge effort...

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java (hunk 28 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:108]: Yes, the original intent of having the `NON_NORMALIZED` item was token the constructors default behavior. There are no tests at many places and my knowledge how things are supposed to work is very limited, hence I tried to make this change as minimal in first. Reworking it to `NORMALIZED` now feels as an avoidable mistake.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java (hunk 26 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java]: I have now complemented the missing part.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java (hunk 27 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXMLPropertiesDisabler.java]: The Javadoc is now clear on that this constructor is primarily intended for testing and that `os` represents the OS to be used.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMIntrinsic.java (hunk 29 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMIntrinsic.java]: Reverted to previous state.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMNodes.java (hunk 30 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMNodes.java]: Reverted.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMObject.java (hunk 31 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMObject.java]: Reverted

File: kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/NonNormalized_Accordion.fxml (hunk 33 above)
Comment (Oliver-Loeffler) [reply kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/NonNormalized_Accordion.fxml]: Changed to CamelCase writing.

File: kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/Normalized_Accordion.fxml (hunk 34 above)
Comment (Oliver-Loeffler) [reply kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/Normalized_Accordion.fxml]: Changed to CamelCase writing.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java (hunk 35 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java]: This was an accident. This file was kind of one of the hardest files to edit, looks all the same, IDE gets sluggish. Sorry for that.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java (hunk 28 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:108]: Following locations require an update:

Kit:
* `com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest` line 286
* `com.oracle.javafx.scenebuilder.kit.preview.PreviewWindowController` lines 215, 282, were already okay
* `com.oracle.javafx.scenebuilder.kit.metadata.util.ClipboardDecoder` line 92, required `NORMALIZED`
* `com.oracle.javafx.scenebuilder.kit.library.LibraryItem` line 90 , required `NORMALIZED`
* `com.oracle.javafx.scenebuilder.kit.fxom.FXOMRefresher` line 63 , no switches
* `com.oracle.javafx.scenebuilder.kit.fxom.FXOMNodes` lines 155 and 207, required `NORMALIZED`
* `com.oracle.javafx.scenebuilder.kit.fxom.FXOMArchive` line 76, required `NORMALIZED`
* `com.oracle.javafx.scenebuilder.kit.editor.EditorController` line 2561, requires `NORMALIZED`
* `com.oracle.javafx.scenebuilder.kit.editor.panel.library.LibraryPanelController` line 1004, requires `NORMALIZED`
* `com.oracle.javafx.scenebuilder.kit.editor.panel.ImportWindowController` line561, requires `NORMALIZED`
* `com.oracle.javafx.scenebuilder.kit.editor.job.AddTooltipToSelectionJob`line 136, requires `NORMALIZED`
* `com.oracle.javafx.scenebuilder.kit.editor.job.AddContextMenuToSelectionJob`line 136, requires `NORMALIZED`

This is all places I have identified so far.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java (hunk 32 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java:4476]: So, the test on Windows 10 went fine, the use of system menu bar can be toggled, it saves correctly. When disabled, the property is not set to false, it is removed, which is okay. There is no visual effect in preview, regardless of having the property is enabled or not.

It works for Windows.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java (hunk 28 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:108]: I've provided a commit with the necessary changes.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java (hunk 32 above)
Comment (jperedadnr) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java:4476]: Great!

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java (hunk 28 above)
Comment (jperedadnr) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:108]: Okay, thanks.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java (hunk 21 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java]: Well, I am learning quite a lot now, will see that I can sketch this and add this to the docs folder within the project.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java (hunk 9 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java]: I have learned, that at those places in future I'll put better an explanation why I've decided to work in a certain way, sorry for all the extra runs.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java (hunk 32 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java:4476]: Just finished a test on Ubuntu 20.04 and also here, it works fine.

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMArchive.java [hunk 36]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2019, Gluon and/or its affiliates.
+ * Copyright (c) 2022, Gluon and/or its affiliates.
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMArchive.java:2]: `2019, 2022,`

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMNodes.java [hunk 37]
```diff
@@ -1,4 +1,5 @@
-/*
+/* 
+ * Copyright (c) 2017, 2022, Gluon and/or its affiliates.
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMNodes.java:2]: `Copyright (c) 2022, ...`

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java [hunk 38]
```diff
@@ -80,16 +82,37 @@
...
+     */
+    public FXOMDocument(String fxmlText, URL location, ClassLoader classLoader, ResourceBundle resources, FXOMDocumentSwitch... switches) throws IOException {
         this.glue = new GlueDocument(fxmlText);
         this.location = location;
         this.classLoader = classLoader;
         this.resources = resources;
         initialDeclaredClasses = new ArrayList<>();
         if (this.glue.getRootElement() != null) {
+            String fxmlTextToLoad = fxmlText;
+            if (!Set.of(switches).contains(FXOMDocumentSwitch.FOR_PREVIEW)) {
```
Comment (jperedadnr) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java:109]: Extract `Set.of(switches)` to a variable, so you don't create the set twice?

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMArchive.java (hunk 36 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMArchive.java]: Updated

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMNodes.java (hunk 37 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMNodes.java]: Corrected

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java (hunk 38 above)
Comment (Oliver-Loeffler) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMDocument.java]: There is now on set used for both places where it is required.

**Review by jperedadnr — APPROVED** [review]
Looks good, great job!
