### PR TITLE
fix: Force refresh of theme and stylesheets when swatch color changes

### LINKED ISSUE #764: Changing swatch color doesn't update content/preview after #748
Changing a swatch color from a mobile template doesn't update the color of the content view, nor from the preview (if it is already opened)

### Expected Behavior

The color is updated in content and preview when swatch color changes
### Current Behavior

The color is not updated in content and preview when swatch color changes

### PR DESCRIPTION
**Pull request by jperedadnr**
### Issue

Fixes #764

When the swatch color property changes, the list of external stylesheets applied to the current theme changes too, so the editorController needs to make another call to retrieve those, if any (for instance, when the Gluon plugin is present), and refresh content/preview/... accordingly

### Progress

- [ ] Change must not contain extraneous whitespace
- [ ] License header year is updated, if required
- [ ] The PR name must follow the [pre-defined format](https://github.com/gluonhq/scenebuilder/blob/master/CONTRIBUTING.md)
- [ ] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

File: kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorController.java [hunk 1]
```diff
@@ -580,6 +580,16 @@ public ObservableValue<Theme> themeProperty() {
...
     }
 
+    /**
+     * Refresh the theme and related stylesheets in different
+     * places (content, preview, ...)
+     */
+    public void refreshTheme() {
+        EditorPlatform.Theme currentTheme = getTheme();
+        setTheme(null);
+        setTheme(currentTheme);
```
Comment (abhinayagarwal) [inline kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorController.java:590]: why is setting the theme to `null` required?

Comment (jperedadnr) [reply kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorController.java:590]: EditorController has `themeProperty` with a default theme. When the theme changes, it refresh the scene graph from the `invalidated()` method, and there are a bunch of listeners in different places (5 so far) attached to `themeProperty()` that react accordingly.

For instance, in `ContentPaneController` we have:
```
editorController.themeProperty().addListener((ov, t, t1) -> themeDidChange());
```
that ultimately calls  `EditorPlatform::getStylesheetsForTheme`, that brings in the Gluon plugin stylesheets and the updated swatch color stylesheet.

The easy way to trigger all those listeners is to force an invalidation of `editorController.themeProperty()`, and that's easily done with setting null and restoring the current theme.

**Review by abhinayagarwal — APPROVED** [review]

**Review by johanvos — APPROVED** [review]
