### PR TITLE
fix: update license year using maven build date

### LINKED ISSUE #635: About dialog shows outdated license date
The license year on the about dialog page is fetched from a property file which is often overlooked and may contain out-dated information.

### Expected Behavior

Should use the build year

### Current Behavior

Uses a hardcoded value

### Steps to Reproduce

Run Scene Builder from source

### Your Environment

Mac OS X, aarch64, 13.3.1

### Screenshots

Screenshot 2023-05-08 at 3 53 58 PM

### PR DESCRIPTION
**Pull request by abhinayagarwal**
### Issue

Fixes #635

### Progress

- [x] Change must not contain extraneous whitespace
- [x] License header year is updated, if required
- [x] The PR name must follow the [pre-defined format](https://github.com/gluonhq/scenebuilder/blob/master/CONTRIBUTING.md)
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

**Review by jperedadnr — DISMISSED** [review]
looks good

File: app/src/main/java/com/oracle/javafx/scenebuilder/app/about/AboutWindowController.java [hunk 1]
```diff
@@ -85,6 +88,7 @@ public AboutWindowController() {
                 sbBuildInfo = sbProps.getProperty("build.info", "UNSET"); //NOI18N
                 sbBuildVersion = sbProps.getProperty("build.version", "UNSET"); //NOI18N
                 sbBuildDate = sbProps.getProperty("build.date", "UNSET"); //NOI18N
+                sbBuildDateFormat = sbProps.getProperty("build.date.format", "UNSET"); //NOI18N
```
Comment (jperedadnr) [inline app/src/main/java/com/oracle/javafx/scenebuilder/app/about/AboutWindowController.java:91]: why don't you use directly `maven.build.timestamp.format`?

Comment (abhinayagarwal) [reply app/src/main/java/com/oracle/javafx/scenebuilder/app/about/AboutWindowController.java:91]: trying to keep things as they have been. `maven.build.timestamp` is not used directly and passed via `build.date` instead.

**Review by jperedadnr — APPROVED** [review]
